apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 1000m
        memory: 1000Mi
    tlsSidecar: 
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          cpu: 1000m
          memory: 1000Mi
    template:
      pod:
        metadata:
          labels:
            app.kubernetes.io/instance: mycluster
            app.kubernetes.io/managed-by: me 
            app.kubernetes.io/name: name
          annotations:
            productID: id
            productName: name 
            productVersion: v
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                    - amd64 
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.3"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    template:
      pod:
        metadata:
          labels:
            app.kubernetes.io/instance: mycluster
            app.kubernetes.io/managed-by: me 
            app.kubernetes.io/name: name
          annotations:
            productID: id
            productName: name 
            productVersion: v
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                    - amd64 
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 1000m
        memory: 1000Mi
    tlsSidecar: 
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          cpu: 1000m
          memory: 1000Mi
  entityOperator:
    template:
      pod:
        metadata:
          labels:
            app.kubernetes.io/instance: mycluster
            app.kubernetes.io/managed-by: me 
            app.kubernetes.io/name: name
          annotations:
            productID: id
            productName: name 
            productVersion: v
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                    - amd64 
    tlsSidecar:
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          cpu: 1000m
          memory: 1000Mi
    topicOperator:
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          cpu: 1000m
          memory: 1000Mi
    userOperator:
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
        limits:
          cpu: 1000m
          memory: 1000Mi
