apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    image: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-s390x:ubi
    tlsSidecar:
      image: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-s390x:ubi
    version: 2.3.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: ephemeral
  zookeeper:
    image: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-s390x:ubi
    tlsSidecar:
      image: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/kafka-s390x:ubi
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      image: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator-s390x:ubi
    userOperator:
      image: hyc-qp-stable-docker-local.artifactory.swg-devops.com/strimzi/operator-s390x:ubi
